### ISSUE TITLE
CHIA support for Flexpool

### ISSUE THREAD

**Issue by ebeng** [jouir/mining-dashboards#8]
Is there any way we could transform this into also retrieving information for CHIA on Flexpool?
Probably it is a matter of replacing some API calls and some name from ETH to CHIA, but how?

**Comment by jouir** [comment]
Chia support has been added.
There is now a `COIN` environment variable in `docker/environment` file (`xch` and `eth` supported).
All the dependent dashboards have been updated to include a `coin` variable at the top and deduce miners automatically.

**Comment by ebeng** [comment]
Awesome!!! I will fetch and see how this is working! Really appreciated!!

**Comment by ebeng** [comment]
I pulled everything new from the Gitlab, but getting the following error now: 

```
sudo docker-compose up -d
Creating network "mining-dashboards_default" with the default driver
Pulling telegraf (telegraf:1.19.2)...
1.19.2: Pulling from library/telegraf
1cfaf5c6f756: Pull complete
c4099a935a96: Pull complete
f6e2960d8365: Pull complete
3d5cf88f7c51: Pull complete
94e4ada2757a: Pull complete
7a9d197c0f2b: Pull complete
e2bcb12e8f8a: Pull complete
Digest: sha256:266487732596eb1df84950eac64b92193f0a625d7eb49ccef536e9c86785719e
Status: Downloaded newer image for telegraf:1.19.2
Creating influxdb ... done
Creating grafana  ...
Creating telegraf ...
Creating grafana  ... done
ERROR: for telegraf  a bytes-like object is required, not 'str'

ERROR: for telegraf  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.22/containers/621a40                                                                      f0e35d1db828b9157778c7ed3ea10ecd57889049166a66f73157df5571/start


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'failed to create shim: OCI runtime create failed: container                                                                      _linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mo                                                                      unting "/home/ubuntu/mining-dashboards/docker/telegraf.conf" to rootfs at "/etc/telegraf/telegraf.conf" caused: mount                                                                       through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if                                                                       the specified host path exists and is the expected type'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 545, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 460, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 465, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 457, in create_and_start
    self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'


```

**Comment by ebeng** [comment]
deleted everything, the folder/directory, git clone again and now it does not pop up the error
